#!/bin/bash

echo "Yeah! We will try to smash the root detection. I hope I won't fail you!\n"
echo "Authors: SK, Icarott, n3k00n3"


# Device Connection
echo -e "\e[00;34m[-] Are you already connected to the device? (yes or no)\e[00m"
read connect
if [ $connect != "yes" ]; then
  echo " " 
  echo -e "\e[1;34m[-] What's the device's IP address?\e[00m"
  read ip
  adb connect $ip
fi


# Frida-Server Service
echo ""
if adb shell pidof frida-server >/dev/null
then
	echo -e "\e[1;93m[+] Frida Running\e[0m"
else
	echo -e "\e[1;93m[!] Starting Frida\e[0m\n\n"
	adb shell /data/local/tmp/frida-server &
fi	

# Packages List
echo ""
echo -e "\e[1;92m[+] - Listing the applications\e[0m"
echo ""
adb shell pm list packages -3 | cut -d ":" -f2

# Set App Package
echo ""
echo -e "\e[1;93m[-] Which application? (package name e.g com.example.app)\e[0m"
read app

echo " "
echo -e "\e[1;92m[+] - Listing the application classes\e[0m"
echo " "
objection -g $app run "android hooking list classes" | grep "$app"


echo -e "\e[1;92m[-] Would you like to hook all classes? [Y or N]\e[0m" 
read hookar
if [ $hookar = "Y" ]; then
  objection -g $app run "android hooking list classes"
else
  echo " "
  echo -e "\e[1;91m[+] - Don't worry, we are trying one last option. Running codeshare scripts..\e[0m"
  frida --codeshare dzonerzy/fridantiroot -U -f $app --no-pause
  exit
fi


echo " "
echo -e "\e[1;93m[+] Set the class:\e[0m"
read class
echo " "
echo -e "\e[1;92m[+] - Listing the methods of the application class\e[0m"
echo " "
objection -g $app run "android hooking list class_methods $class" | grep "boolean" | rev | cut -d "." -f1 | rev
sed -i "s/var target = asd/var target = Java.use(\"$class\");/g" rootbypass.js

echo " "
echo -e "\e[1;94m[-] What's the bypass method?\e[0m e.g. isSuperUser"
read method
echo " "
echo -e "\e[1;96m[+] - Bypassing the method $method\e[0m"
sed -i "s/target.implementation/target.$method.implementation/g" rootbypass.js
echo " "
frida -U -f $app -l rootbypass.js --no-pause
