#!/bin/bash

figlet SmashDevice -t 
echo "Collaborators: SK & Icarott"
echo "Yeah! We will try to smash the root detection. I hope I won't fail you!"
echo "TODO: Destruction of other protections"

creator(){
cat > rootbypass.js << EOF
'use strict'

if (Java.available){

  Java.perform(function(){

    try{

    var target = asd

    target.implementation = function () {
    console.log('');
    console.log('[+] Bypassed Root Detection, Enjoy!');

    return false;
    };

    }
    catch(error){
      console.log("[-] An exception occured");
      console.log(String(error.stack));
    }
  });
}
else{

console.log("[-] Java is not available");
}
EOF
}

creator

ADB=$(which adb);
if [[ -e $ADB ]]
then
	2>&1
else
	echo " "
	echo -e "\e[1;34m[+] - Installing ADB\e[0m"
	apt install adb -y
fi

echo " "
echo -e "\e[1;34m[-] Are you already connected to the device? (yes or no)\e[0m"
read connect
if [ $connect = "yes" ]
  then
     2>&1
else
  echo " " 
  echo -e "\e[1;34m[-] What's the device's IP address?\e[0m"
   read ip
   adb connect $ip
fi

OBJECTION=$(which objection);
if [[ -e $OBJECTION ]]
then
        echo 2>&1
else
        echo " "
        echo -e "\e[1;34m[+] - Installing Objection\e[0m"
        pip3 install objection
        echo " "
fi

FRIDA=$(which frida);
if [[ -e $FRIDA ]]
then
        2>&1
else
        echo " "
        echo -e "\e[1;34m[+] - Installing Frida-Tools\e[0m"
        pip3 install frida-tools
fi

if adb shell pidof frida-server >/dev/null
then
	echo -e "\e[1;93m[+] Frida Running\e[0m"
else
	echo -e "\e[1;93m[!] Starting Frida\e[0m"
	adb shell /data/local/tmp/frida-server &
fi	

echo " "
echo -e "\e[1;92m[+] - Listing the applications\e[0m"
echo " "
adb shell pm list packages -3 | cut -d ":" -f2
echo " "
echo -e "\e[1;93m[-] Which application? (package name e.g com.example.app)\e[0m"
read app

echo " "
echo -e "\e[1;92m[+] - Listing the application classes\e[0m"
echo " "
objection -g $app run "android hooking list classes" | grep "$app"

echo " "
echo -e "\e[1;92m[-] Did you find the class? [Y or N]\e[0m" 
read find
if [ $find = "Y" ] 
then 
  2>&1
else 
 echo -e "\e[1;92m[-] Would you like to hook all classes?\e[0m" 
read hookar
if [ $hookar = "Y" ]
then
  objection -g $app run "android hooking list classes"
else
  echo " "
  echo -e "\e[1;91m[+] - Don't worry, we are trying one last option. Running codeshare scripts..\e[0m"
  frida --codeshare dzonerzy/fridantiroot -U -f $app --no-pause
  exit
fi
fi

echo " "
echo -e "\e[1;93m[+] Set the class:\e[0m"
read class
echo " "
echo -e "\e[1;92m[+] - Listing the methods of the application class\e[0m"
echo " "
objection -g $app run "android hooking list class_methods $class" | grep "boolean" | rev | cut -d "." -f1 | rev
sed -i "s/var target = asd/var target = Java.use(\"$class\");/g" rootbypass.js

echo " "
echo -e "\e[1;94m[-] What's the bypass method?\e[0m e.g. isSuperUser"
read method
echo " "
echo -e "\e[1;96m[+] - Bypassing the method $method\e[0m"
sed -i "s/target.implementation/target.$method.implementation/g" rootbypass.js
echo " "
frida -U -f $app -l rootbypass.js --no-pause
